import { icons } from "./assets/icons";

export const levels = [
  { name: "novice", color: "#9D9E9E" },
  { name: "apprentice", color: "#7175D6" },
  { name: "adept", color: "#5DAD60" },
  { name: "expert", color: "#C5D321" },
  { name: "master", color: "#A062C9" },
];

const content = [
  [
    {
      name: "miner",
      description: "miner: extracts ore, precious stones, and minerals",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you're no genius, but with some luck you can pull out a few chunks of iron ore. quicksilver or, say, corundum is clearly beyond you",
        "you've learned to handle a pickaxe — not with mastery, but decently. you're good at mining iron, the most common metal",
        "you could say you've succeeded at mining. now you can extract corundum and quicksilver, and you've mastered the chief rule for orichalcum — don't get caught by orcs",
        "you've learned to tell moonstone from other minerals. rare metals like gold or silver require knowledge, and you have it",
        "your beard is thicker and the collar of your knit sweater is higher — every stone in a backwoods gully is your informant, because you know how to pull something valuable from it: malachite, maybe even ebony",
      ],
      icon: icons["miner"],
    },
    {
      name: "fishman",
      levelsPrice: [50, 70, 90, 110],
      description: "fisherman: catches fish",
      levelsDescription: [
        "you know a fishing rod exists, and that bait goes on a hook. you even know you should cast the line and watch the float — but does that guarantee a catch? i doubt it",
        "you've grasped the basics of fishing and now know river fish are best caught with a bee or a luna moth wing",
        "through long trips and hours spent fishing, you learned that lake fish love dragonflies most, while fish in dungeons greedily snap at any bait",
        "you're already an experienced angler: you know sea fish bite well on blue butterfly and monarch, and predator fish in any body of water will go for a baitfish",
        "you fish masterfully — many think you are simply lucky. but you know the right spot, matching bait, and steady hands matter far more",
      ],
      icon: icons["fishman"],
    },
    {
      name: "saltmaker",
      levelsPrice: [50, 80, 110, 140],
      description: "tradesman: digs clay and salt, produces glass and clay goods",
      levelsDescription: [
        "when an employer asks what you can do, you usually say: “i can dig clay.” when he asks what else, you think and reply: “well, i can not dig...”",
        "you're a true wizard. with a shovel and some colorful language you can make clay pots, sand glass, and salt from seawater",
        "you've perfected glassblowing and can shape complex vessels. your knack for digging in the right direction uncovers precious nuggets on clay riverbanks",
        "as a practical and sharp-witted person, you don't dream of magical treats, but you understand how to refine your work — do less, get more",
        "among tradesmen, legends circulate about your luck and amazing productivity. you are truly a master, and your shovel deserves a gold bust",
      ],
      icon: icons["saltmaker"],
    },
    {
      name: "hunter",
      description: "hunter: obtains hides and meat from wild animals",
      levelsPrice: [50, 70, 90, 110],
      levelsDescription: [
        "hunting isn't easy, especially for a beginner. you need to know too much just to catch a nimble rabbit or a mudcrab",
        "you've mastered the basics of hunting, but lack practice — you often ruin hides and ingredients trying to dress a carcass in the field",
        "you've hunted for a while now and can extract the most valuable ingredients, but you're still not careful enough skinning away from the butcher's table",
        "you're an experienced hunter — your prey grows larger and your butchering skill is good enough to stay far from the cities for long stretches",
        "you know where to find rare animals and how to hunt them. you don't slip when skinning or harvesting valuable ingredients",
      ],
      icon: icons["hunter"],
    },
    {
      name: "doctor",
      description: "herbalist: gathers herbs, mushrooms, and berries",
      levelsPrice: [50, 70, 90, 110],
      levelsDescription: [
        "perhaps all your plant knowledge comes from grandma's stories about edible berries. however, your last stomach upset makes you doubt her competence",
        "“a primer for the barbarian” helped you identify some plants — now you know how to pick a bluebell without attracting minotaurs",
        "you've always loved mushrooms but hated picking them. time to change. you know a lot about mushrooms and can easily tell which one poisoned you yesterday",
        "your wanderings through forests, fields, and caves weren't wasted — you know herbs, berries, and mushrooms well. you even have your own secret spots, the pride of any herbalist",
        "you've reached the pinnacle of herbalism. you can tell one plant from another at a distance. your clothes smell of flowers, no worse than telvanni beetle musk",
      ],
      icon: icons["doctor"],
    },
    {
      name: "woodcutter",
      description: "woodcutter: harvests timber, fells trees, and chops firewood",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you can break branches and strip bark — even children can manage that. you can hold an axe, but it keeps trying to find your foot",
        "you've learned the basics of chopping wood and felling trees properly — your companions no longer fear you'll drop a spruce on their heads. you've barely learned charcoal burning",
        "you've mastered the finer points of charcoal production and learned to make potash. your timber skills have improved considerably",
        "every day you grow more skilled in your craft. you've gotten much stronger — chopping a woodpile three cubits high is nothing to you",
        "you've reached the peak of mastery. the axe slices wood like butter and your arms never tire. you are strong, enduring, and deserve a wooden medal",
      ],
      icon: icons["woodcutter"],
    },
    {
      name: "bee",
      description: "beekeeper: raises bees and gathers honey",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "if a hive has no honey, then wrong bees must have made it — so you think. these fierce creatures have stung you many times, yet you still managed to snag some honey",
        "you know a bit more about bees now and realized a successful peek into a hive isn't everything. you've also picked up beeswax production from honeycomb",
        "you can breed bees and slip prepared wax foundations into the hive. who knew it's much easier to harvest honey this way than to raid wild hives",
        "your apiary's productivity grows; you know how to handle these sweet little creatures that give such a valuable product",
        "you've reached the peak of beekeeping — you know how to breed and feed bees and have perfected honeycomb processing and wax foundation making",
      ],
      icon: icons["bee"],
    },
    {
      name: "farmer",
      description: "farmer: grows and harvests vegetables, raises chickens and cows",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you know how to dig potatoes. you do, right?",
        "a farmer has many tasks: tending crops, milking cows, feeding chickens, collecting eggs, hauling manure, stocking the cellar for winter. you can do all this, but mediocrely",
        "cheese and butter production grows, harvests increase, yields rise, and the chickens lay like mad. an idyll built on your labor",
        "you've mastered many clever tricks and unique methods. boosting yields is your whole thing — just don't let beggars past the fence; they'll trample crops and ruin more than they steal",
        "your parents envy your farming success; you are a master without a doubt. even if your parents don't envy you, someone's parents surely do. in fact, everyone envies you",
      ],
      icon: icons["farmer"],
    },
  ],
  [
    {
      name: "armor",
      description: "armorsmith: forges metal armor",
      levelsPrice: [50, 80, 110, 280],
      levelsDescription: [
        "you're only slightly familiar with smithing, but you have a notion of how to forge useful tools like pickaxes, axes, shovels, and such",
        "your hands are black and your apron is sooty. you've learned to work iron — to cut and smelt metal. forging basic stock poses no difficulty",
        "this month you learned to work with alloys. you can now use steel, moonstone, and silver.",
        "you've become an experienced armorsmith. you unlock new alloys: quicksilver and elven gilded.",
        "a master armorsmith can do it all — there's no material you can't work with, so it's time to master the techniques of your people. you've also learned to use dwemer recipes adventurers drag from ruins.",
      ],
      icon: icons["armor"],
    },
    {
      name: "weapon",
      description: "weaponsmith: forges metal weapons",
      levelsPrice: [50, 80, 110, 280],
      levelsDescription: [
        "you're only slightly familiar with smithing, but you have a notion of how to forge useful tools like pickaxes, axes, shovels, and such",
        "your hands are black and your apron is sooty. you've learned to work iron — to cut and smelt metal. forging basic stock poses no difficulty",
        "this month you learned to work with alloys. you can now use steel, moonstone, and silver.",
        "you've become an experienced weaponsmith. you unlock new alloys: quicksilver and elven gilded.",
        "a master weaponsmith can do it all — there's no material you can't work with, so it's time to master the techniques of your people. you've also learned to use dwemer recipes adventurers drag from ruins.",
      ],
      icon: icons["weapon"],
    },
    {
      name: "jewelry",
      description: "jeweler: crafts jewelry",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "“sigurd — you're a jeweler!” usually said to someone who can do very fine work. it does not apply to you",
        "you can do something — stringing wooden beads or tying a cheap shiny stone to a thread. the ceiling of your skill is amulets of the divines",
        "with clay molds you cast metal for amulets, rings, circlets, and candlesticks. you can also draw wire that makes decent chains",
        "your skill grows; you use the cutting bench with ease and can now inlay certain precious stones into your elegant metal pieces",
        "you're a master, what more can be said. you can forge and polish any piece. you take pride in jewels set with rare stones whose cuts you've perfected",
      ],
      icon: icons["jewelry"],
    },
    {
      name: "leather",
      description: "tanner: treats hide and creates leather goods",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you can scrape a thin hide clean and cut leather into roughly even strips or laces, but everything else is a dark forest to you",
        "you've spent plenty of time combing and dressing furs. from now on you can make fur armor and other goods from this material",
        "you've mastered the basics: rawhide, pickled leather, and even tanning. your work isn't limited to armor — you make excellent packs, bags, and boots",
        "you've learned to craft complex leather goods and handle materials that are easy to ruin with ease. you've also mastered dyeing various types of leather",
        "you can craft the most beautiful and complex items. legends tell of the quality of your leather, and jarls and their courtiers strut about in your furs",
      ],
      icon: icons["leather"],
    },
    {
      name: "clother",
      description: "tailor: sews various kinds of clothing",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you know that in skyrim mountain flower is used to make linen fabrics — it's a close relative of flax. that is where your weaving knowledge ends",
        "you've learned to process mountain flower into linen thread, use dye, and make linen fabrics. you can sew simple linen clothes",
        "you've learned to process fleece and cottongrass into cotton and wool, and to make cotton and wool fabrics. you can sew simple cotton and blended clothing",
        "you've mastered most fabric-working techniques, including complex dyeing. you freely use furs and different materials in your work",
        "you've mastered every type of fabric and can combine them. you've become so skilled that nobles and jarls are ready to buy your clothing",
      ],
      icon: icons["clother"],
    },
    {
      name: "carpenter",
      description: "carpenter: makes various wooden goods — bows, shields, and crossbows",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "the neighbor taught his little son to make stools — how are you any worse? you can make a passable axe haft or a shovel shaft",
        "excellent, you've learned to make something useful. you can now make training weapons for warriors and decent travel staves for mages and travelers",
        "your carpentry knowledge is at a baseline level. you can work wood to make bows, shields, battle staves, and simple crossbows",
        "your skill grows — you've learned to make various weapons with metal components: bows, shields, crossbows. you've also mastered carving not only wood but bone.",
        "master bowyer — a title you can wear with pride. your bows and crossbows are powerful, made from the finest wood, and can feature a unique upgrade: a sight",
      ],
      icon: icons["carpenter"],
    },
    {
      name: "somelie",
      description: "brewer: brews mead and makes wine",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "this profession is currently under development — look for something else or wait for it to be implemented",
        "this profession is currently under development — look for something else or wait for it to be implemented",
        "you're growing more experienced — you can work with vintage meads and wines, but you still occasionally lose a batch or two to poor storage or some other slip",
        "you're half a step away from rightfully being called a master. you can make any drink — sometimes you produce true alcoholic masterpieces",
        "you've become a master and learned to produce the rarest spirits on a steady basis — your goods taste excellent and are valued even beyond skyrim",
      ],
      icon: icons["somelie"],
    },
    {
      name: "chief",
      description: "cook: prepares food",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you can roast a skeever over a fire and slice cheese — what more does a simple laborer need?",
        "you've learned simple baking — bread comes out crusty and tender, and roasted meat no longer looks like a charcoal lump from the fire",
        "your list of signature dishes keeps growing. you cook meat and fish well, know a thousand and one soup recipes, and don't turn your nose up at mushrooms on the coals",
        "you've learned to cook the favorite food of children and the secret passion of adults — sweet rolls and other treats. you also know how to cook horker and rare fish",
        "you've reached the peak of the culinary arts — the servers call you chef, and your knowledge of rare dishes and delicate appetizers makes other cooks jealous",
      ],
      icon: icons["chief"],
    },
  ],
  [
    {
      name: "daggers",
      description: "assassin: specializes in daggers and stealth",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "once, as a child, you were given a knife — it was small and dull, just like you",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, fast, and move nimbly in stealth",
        "who said the left hand is less agile than the right? you've trained enough to use both hands effectively",
        "years of persistent training pay off — every technique of dagger combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["daggers"],
    },
    {
      name: "shortswords",
      description: "scout: specializes in short blades and stealth",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you could never figure it out: is this a big dagger or a small sword?",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, fast, and move nimbly in stealth",
        "who said the left hand is less agile than the right? you've trained enough to use both hands effectively",
        "years of persistent training pay off — every technique of short-blade combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["shortswords"],
    },
    {
      name: "swords",
      description: "knight: specializes in one-handed swords",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "the best spell against unpleasant encounters is a double-edged sword",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "who said the left hand is less agile than the right? you've trained enough to use both hands effectively",
        "years of persistent training pay off — every technique of one-handed sword combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["swords"],
    },
    {
      name: "scimitar",
      description: "forerunner: specializes in weapons rare to Skyrim — sabers and scimitars",
      levelsPrice: [50, 80, 110, 280],
      levelsDescription: [
        "they have curved swords... curved... swords...",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "who said the left hand is less agile than the right? you've trained enough to use both hands effectively",
        "years of persistent training pay off — every technique of saber and scimitar combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["scimitar"],
    },
    {
      name: "katana",
      description: "spy: specializes in weapons rare to Skyrim — katana, tanto, and wakizashi",
      levelsPrice: [50, 80, 110, 280],
      levelsDescription: [
        "your mentor advised you to stay away from the wild nords — so what are you doing in skyrim?",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "who said the left hand is less agile than the right? you've trained enough to use both hands effectively",
        "years of persistent training pay off — every technique of katana combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["katana"],
    },
    {
      name: "mace",
      description: "rogue: specializes in clubs and maces",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "why try to stab someone when you can just whack them over the head?",
        "you trained long and honed basic club attacks to reflex, but your special techniques still look rather ridiculous",
        "you trained long and honed basic mace attacks to reflex, but your special techniques still look rather ridiculous",
        "you've trained enough to use both hands effectively, and your special techniques are no longer embarrassing to show in public",
        "years of persistent training pay off — every technique of club, hatchet, and mace combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["mace"],
    },
    {
      name: "axes",
      description: "berserker: specializes in one-handed axes",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "in deep antiquity an unknown force cleaved all existence in two with an axe — however, no one believes this story of yours",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "who said the left hand is less agile than the right? you've trained enough to use both hands effectively",
        "years of persistent training pay off — every technique of one-handed axe combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["axes"],
    },
    {
      name: "hammer",
      description: "brawler: specializes in one-handed hammers",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "one day you realized your fingers and a hammer are best friends... at least, until you try to drive nails",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "who said the left hand is less agile than the right? you've trained enough to use both hands effectively",
        "years of persistent training pay off — every technique of one-handed hammer combat is available to you. you've reached the highest level of mastery with this weapon",
      ],
      icon: icons["hammer"],
    },
  ],
  [
    {
      name: "bows",
      description: "archer: specializes in bows and crossbows",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "anyone can string a stick — shooting with it, now...",
        "hour-long ambushes in the bushes are useful — they let you take careful aim and make a killing shot",
        "your eyesight sharpens with training — squinting, you can make out very distant targets, something not everyone can do",
        "your dexterity lets you pull arrows from the quiver much faster than any beginner",
        "being a master means you're so used to your bow that you move quite fast even with the string drawn",
      ],
      icon: icons["bows"],
    },
    {
      name: "longsword",
      description: "swordsman: specializes in two-handed swords",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "they aren't really greatswords, they're longswords — though some truly are great... but let's not argue about size",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "you've grown stronger and know every combat technique, yet despite your new strength some of them are still hard to execute",
        "years of persistent training pay off — you move lightly and freely. what was once a difficult trick has become a routine technique. that is mastery",
      ],
      icon: icons["longsword"],
    },
    {
      name: "greatkatana",
      description: "blade: specializes in enormous katanas — nodachi",
      levelsPrice: [50, 80, 110, 280],
      levelsDescription: [
        "the art of the nodachi has long been lost. some old dunmer may still remember those flashy techniques, but alas this weapon's mastery is unlikely ever to return to tradition",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "you've grown stronger and know every combat technique, yet despite your new strength some of them are still hard to execute",
        "years of persistent training pay off — you move lightly and freely. what was once a difficult trick has become a routine technique. that is mastery",
      ],
      icon: icons["greatkatana"],
    },
    {
      name: "battleaxe",
      description: "slasher: specializes in two-handed axes and battleaxes",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "about such a person they say: “a real slasher of a lad”",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "you've grown stronger and know every combat technique, yet despite your new strength some of them are still hard to execute",
        "years of persistent training pay off — you move lightly and freely. what was once a difficult trick has become a routine technique. that is mastery",
      ],
      icon: icons["battleaxe"],
    },
    {
      name: "warhammer",
      description: "crusher: specializes in two-handed hammers",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "a hammer is a universal tool — crack a couple of skulls, drive a bolt... anything",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "you've grown stronger and know every combat technique, yet despite your new strength some of them are still hard to execute",
        "years of persistent training pay off — you move lightly and freely. what was once a difficult trick has become a routine technique. that is mastery",
      ],
      icon: icons["warhammer"],
    },
    {
      name: "staff",
      description: "monk: specializes in battle staves",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "when you want to grab some cudgel and whack it good and proper across a swineherd's spine",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "you've grown stronger and know every combat technique, yet despite your new strength some of them are still hard to execute",
        "years of persistent training pay off — you move lightly and freely. what was once a difficult trick has become a routine technique. that is mastery",
      ],
      icon: icons["staff"],
    },
    {
      name: "pike",
      description: "spearman: wields one-handed spears, two-handed pikes, and exotic tridents",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "not the flashiest weapon, but very effective — for those who like to approach from afar",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "you've grown stronger and know every combat technique, yet despite your new strength some of them are still hard to execute",
        "years of persistent training pay off — you move lightly and freely. what was once a difficult trick has become a routine technique. that is mastery",
      ],
      icon: icons["pike"],
    },
    {
      name: "halberd",
      description: "guardsman: specializes in halberds and can also master exotic glaives",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "i have a spear, i have a battleaxe... mmm... halberd",
        "you trained long and honed basic attacks to reflex, but your special techniques still look rather ridiculous",
        "not much time passed and you mastered your special techniques — now you're graceful, and your duels are well worth watching with unhidden interest",
        "you've grown stronger and know every combat technique, yet despite your new strength some of them are still hard to execute",
        "years of persistent training pay off — you move lightly and freely. what was once a difficult trick has become a routine technique. that is mastery",
      ],
      icon: icons["halberd"],
    },
  ],
  [
    {
      name: "armorlight",
      description: "infantryman: wears light armor",
      levelsPrice: [50, 80],
      levelsDescription: [
        "you put on armor for the first time — it's uncomfortable and hot",
        "the armor no longer feels so uncomfortable, especially since you asked the smith to fit it to your build. it restricts your movement much less",
        "long use of armor has made your body adapt to the load — you no longer feel its weight or struggle to move while blocking the enemy's blows.",
      ],
      icon: icons["armorlight"],
    },
    {
      name: "armorheavy",
      description: "man-at-arms: wears heavy armor",
      levelsPrice: [80, 110],
      levelsDescription: [
        "you put on armor for the first time — it's uncomfortable, pinches under the arms, and chafes your neck",
        "the armor no longer feels so uncomfortable, especially since you asked the smith to fit it to your build. falls from height will now be less painful.",
        "long use of armor has made your body adapt to the load — you no longer feel its weight or struggle to move while blocking the enemy's blows.",
      ],
      icon: icons["armorheavy"],
    },
    {
      name: "shield",
      description: "shield-bearer: specializes in fighting with a shield",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "you can hold a shield, thank the gods. it's heavy and not very comfortable — you should practice",
        "you've mastered one of the shield-bearer's key techniques — a shield bash. this move costs a lot, but the result pays it back",
        "regular shield practice has given you both confidence in battle and enough conditioning to run with your shield proudly raised.",
        "you're so used to the shield — its weight and dimensions — that raising a block no longer slows you down",
        "mastery comes with time — after many hours of shield practice you learned you can block even the magic of less-than-clever creatures at the right angle.",
      ],
      icon: icons["shield"],
    },
    {
      name: "alchemy",
      description: "alchemist: brews potions, mixes dyes, and applies healing bandages",
      levelsPrice: [50, 80, 110, 140],
      levelsDescription: [
        "your alchemy knowledge ends with standing at the alchemy bench and clacking a pestle against an empty mortar with a wise look",
        "you've mastered the basics of brewing and can make the weakest versions of the most common potions. you've also learned to make healing bandages and ordinary dyes",
        "you've learned to brew potions for every common skyrim ailment and can make stronger versions of other potions and concentrated dyes",
        "you've expanded your arsenal of magical effects through experimentation with ingredients — you now have more ways to brew the same potion",
        "years of practice have raised your skill to an unreachable level. you can make perfect restore health and stamina potions, among many others",
      ],
      icon: icons["alchemy"],
    },
    {
      name: "conjuration",
      description: "conjurer: practices the school of conjuration",
      levelsPrice: [110, 180, 250, 330],
      levelsDescription: [
        "for now this profession only lets you summon weapons — so you can't run around with a spectral wolf",
        "you've mastered the basics of conjuration and can now summon a dagger or a staff. that's as far as your persistence goes for now.",
        "you've reached a new level of conjuration — your spell list has grown: you can summon a katana and a bow, and the power of all summoned weapons has noticeably increased.",
        "your studies bear ever more fruit, making you an expert. you've learned to summon spears, battleaxes, and halberds, and every summoned weapon becomes deadlier in your hands.",
        "you've become a master of conjuration. summoned weapons have revealed their full terrifying potential, and summoned armor, shield, and sword have joined the list.",
      ],
      icon: icons["conjuration"],
    },
    {
      name: "enchant",
      description: "enchanter: applies enchantments to various items",
      levelsPrice: [50, 80, 110, 410],
      levelsDescription: [
        "enchanting is a very complex magical discipline that you only know by hearsay",
        "you've learned to enchant simple battle staves — not the pinnacle of mastery, but everyone starts somewhere",
        "your skills grow — you can now enchant true magical staves that focus a mage's power and even glow pleasantly in the dark",
        "with every day of practice your abilities become more useful. you've learned to enchant battle staves of expensive materials and jewelry",
        "gray hair and a beard are the eternal companions of masters. you've learned to enchant the rarest staves and most valuable jewelry, and magical items drain more slowly in your hands",
      ],
      icon: icons["enchant"],
    },
    {
      name: "alteration",
      description: "mystic: practices the school of alteration",
      levelsPrice: [110, 180, 250, 330],
      levelsDescription: [
        "this profession has a few spells implemented but is still under development — if you enjoy playing a mage just for the dice, feel free to pick it",
        "you've conquered the basics of alteration and can learn apprentice spells. you also gain the magelight spell.",
        "you've reached the next rung of alteration and can learn more advanced adept spells, like detect dead or waterbreathing.",
        "you've become an expert in alteration, experienced enough to learn spells like detect life and waterwalking.",
        "you've achieved mastery in alteration — you command this school perfectly!",
      ],
      icon: icons["alteration"],
    },
    {
      name: "destruction",
      description: "sorcerer: practices the school of destruction",
      levelsPrice: [110, 180, 250, 330],
      levelsDescription: [
        "you know there are some mages and they do magic. scary...",
        "you've gotten stronger in the basics of destruction and can now learn apprentice spells like snowball, and you also receive the flash spell",
        "you've reached the next rung of destruction — your spells deal more damage, and you can learn adept incantations like fire arrow.",
        "you've become an expert in destruction — your spells are even deadlier, and your experience helps you learn very dangerous expert incantations like fireball. you also receive the fire arrow spell.",
        "you've achieved mastery in destruction — your spells have revealed their full potential and you can now learn the most dangerous of them, like comet or cyclone",
      ],
      icon: icons["destruction"],
    },
    {
      name: "illusion",
      description: "illusionist: practices the school of illusion",
      levelsPrice: [110, 180, 250, 330],
      levelsDescription: [
        "this profession has a few spells implemented but is still under development — if you enjoy playing a mage just for the dice, feel free to pick it",
        "you've figured out the basics of illusion and can now learn apprentice spells.",
        "you've mastered the next rank of illusion and can now learn adept spells.",
        "you've mastered the next rank of illusion and can now learn expert spells.",
        "you've achieved mastery in illusion — you command this school perfectly!",
      ],
      icon: icons["illusion"],
    },
    {
      name: "restoration",
      description: "healer: practices the school of restoration",
      levelsPrice: [110, 180, 250, 330],
      levelsDescription: [
        "you know there are mages who can heal with a touch — you usually find them in a temple",
        "you've learned the basics of restoration and can study apprentice spells like healing hands; you also receive the fast healing spell and can examine the wounded to assess their injuries.",
        "the power of your spells has increased — they restore more health, and you are ready to learn adept spells like cure wounds and heal other, capable of healing grave injuries.",
        "you've become an expert of restoration and the power of your spells has grown. you can now study expert spells such as stream of the healing aura. you also receive the heal other spell.",
        "you've achieved mastery in restoration — your spells have revealed their full potential. you can now learn master spells like sphere of great healing.",
      ],
      icon: icons["restoration"],
    },
  ],
];

export const mapper = {
  miner: [0, 0],
  fishman: [0, 1],
  saltmaker: [0, 2],
  hunter: [0, 3],
  doctor: [0, 4],
  woodcutter: [0, 5],
  bee: [0, 6],
  farmer: [0, 7],
  armor: [1, 0],
  weapon: [1, 1],
  jewelry: [1, 2],
  leather: [1, 3],
  clother: [1, 4],
  carpenter: [1, 5],
  somelie: [1, 6],
  chief: [1, 7],
  daggers: [2, 0],
  shortswords: [2, 1],
  swords: [2, 2],
  scimitar: [2, 3],
  katana: [2, 4],
  mace: [2, 5],
  axes: [2, 6],
  hammer: [2, 7],
  bows: [3, 0],
  longsword: [3, 1],
  greatkatana: [3, 2],
  battleaxe: [3, 3],
  warhammer: [3, 4],
  staff: [3, 5],
  pike: [3, 6],
  halberd: [3, 7],
  armorlight: [4, 0],
  armorheavy: [4, 1],
  shield: [4, 2],
  conjuration: [4, 3],
  alchemy: [4, 4],
  enchant: [4, 5],
  alteration: [4, 6],
  destruction: [4, 7],
  illusion: [4, 8],
  restoration: [4, 9],
} as {
  [key: string]: number[];
};

export default content;
