import { ClientListener, CombinedController, Sp } from "./clientListener";
import { logTrace } from "../logging";

const eventNames = [
  "ipcMessage",
  "skyrimLoaded",
  "newGame",
  "preLoadGame",
  "postLoadGame",
  "saveGame",
  "deleteGame",
  "activate",
  "waitStop",
  "moveAttachDetach",
  "lockChanged",
  "grabRelease",
  "cellFullyLoaded",
  "switchRaceComplete",
  "uniqueIdChange",
  "trackedStats",
  "reset",
  "combatState",
  "loadGame",
  "deathEnd",
  "deathStart",
  "containerChanged",
  "hit",
  "unequip",
  "equip",
  "magicEffectApply",
  "effectFinish",
  "effectStart",
  "menuOpen",
  "menuClose",
  "browserMessage",
  "spellCast",
  "open",
  "close",
  // "questInit",
  // "questStart",
  // "questStop",
  // "questStage",
  "sleepStart",
  "sleepStop",
  "waitStart",
  "locationChanged",
  "bookRead",
  "sell",
  "furnitureEnter",
  "furnitureExit",
  "wardHit",
  "packageStart",
  "packageChange",
  "packageEnd",
  "enterBleedout",
  "destructionStageChanged",
  "sceneAction",
  "playerBowShot",
  "fastTravelEnd",
  "perkEntryRun",
  "actionWeaponSwing",
  "actionBeginDraw",
  "actionEndDraw",
  "actionBowDraw",
  "actionBowRelease",
  "actionBeginSheathe",
  "actionEndSheathe",
  "actionSpellCast",
  "actionSpellFire",
  "actionVoiceCast",
  "actionVoiceFire",
  "cameraStateChanged",
  "niNodeUpdate",
  "modEvent",
  "positionPlayer",
  "kinectEvent",
  "deviceConnect",
  "actorKill",
  "criticalHit",
  "disarmedEvent",
  "dragonSoulsGained",
  "itemHarvested",
  "levelIncrease",
  "locationDiscovery",
  "shoutAttack",
  "skillIncrease",
  "soulsTrapped",
  "spellsLearned",
] as const;

export class EventLoggerService extends ClientListener {
  constructor(private sp: Sp, private controller: CombinedController) {
    super();

    const on = this.controller.on as (name: string, cb: (e?: unknown) => void) => void;

    for (const name of eventNames) {
      on(name, (e) => logTrace(this, `test message: ${name} fired`, e ?? ""));
    }
  }
}
