name: Prettier
on: [push, pull_request]
jobs:
  determine-runner:
    runs-on: ubuntu-latest
    concurrency:
      group: runner-determination-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    outputs:
      runner: ${{ steps.set-runner.outputs.use-runner }}
    steps:
      - name: Wait for parallel job startup lag
        run: sleep 15
      - name: Determine runner
        id: set-runner
        uses: mikehardy/runner-fallback-action@v1
        with:
          primary-runner: "self-hosted"
          fallback-runner: "ubuntu-latest"
          fallback-on-error: true
          github-token: ${{ secrets.RUNNER_FALLBACK_TOKEN }}

  prettier:
    name: Prettier
    needs: determine-runner
    runs-on: ${{ fromJson(needs.determine-runner.outputs.runner) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install yarn packages
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd=./misc/prettier install
      - name: Check prettier errors
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd=./misc/prettier prettier-check
        continue-on-error: true
